apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-itby
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-itby
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-itby
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-itby
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-itby
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xtka-tenant/rhtap-demo-app/hacbs-test-project-itby@sha256:a0154f3d0c248b8174a4cb3329373cb6bce6f1e92db5068ba8b38df7ed9b7726
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
