apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-itby
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xtka-tenant/rhtap-demo-app/hacbs-test-project-itby@sha256:a0154f3d0c248b8174a4cb3329373cb6bce6f1e92db5068ba8b38df7ed9b7726
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
